- name: Instalando uma lista de pacotes nos servidores Ubuntu
  hosts: all
  tasks:
  - name: Instalando pacotes
    apt:
      name: "{{ item }}"
    loop:
    - htop
    - nfs-common
    - dnsutils
    when: ansible_distribution == "Ubuntu"
